backend:
  username: "admin"
  password: "0000"

  port: 8888

  jwt:
    secret: "free5gc-it-system"
    expiresIn: 1h

  runnerJwt:
    secret: "free5gc-it-runner"
    expiresIn: 8760h   # 365 * 24
  
  runnerCheckTimeInterval: 10s

  maxHistoryLength: 10

  frontendFilePath: "build/frontend"

  dbPath: ".db/it-system.db"
  logPath: ".db/log"

  discord:
    enabled: true
    webhookUrlPath: ".db/discord_webhook_url"

logger:
  level: "info"