/* tslint:disable */
/* eslint-disable */
/**
 * full-stack-framework API
 * Automatically generated OpenAPI spec from Postman collection \"full-stack-framework\"
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface AddTenantsRequest {
    'tenants': Array<Tenant>;
}
export interface AddTestcasesRequest {
    'testcases': Array<Testcase>;
}
export interface DeleteTenantsRequest {
    'tenants': Array<Tenant>;
}
export interface DeleteTestcasesRequest {
    'testcases': Array<Testcase>;
}
export interface GetGithubPRsResponse {
    'message': string;
    'prs': Array<PR>;
}
export interface GetRunnersResponse {
    'message': string;
    'runners'?: Array<Runner>;
}
export interface GetTenantsResponse {
    'message': string;
    'tenants'?: Array<Tenant>;
}
export interface GetTestcasesResponse {
    'message': string;
    'testcases'?: Array<Testcase>;
}
export interface LoginRequest {
    'username': string;
    'password': string;
}
export interface LoginResponse {
    'message': string;
    'token': string;
}
export interface MessageResponse {
    'message'?: string;
}
export interface NfPr {
    'nfName': string;
    'pr': number;
}
export interface PR {
    'number': number;
    'title': string;
}
export interface RegisterRunnerRequest {
    'name': string;
    'ip': string;
}
export interface RequestRunnerHeartbeat {
    'idle': boolean;
    'onGoingTask'?: number;
}
export interface RequestSubmitTask {
    'tests': Array<string>;
    'nfPrList': Array<NfPr>;
}
export interface RequestTestOutput {
    'endFlag': boolean;
    'id': number;
    'testName'?: string;
    'success'?: boolean;
    'log'?: string;
}
export interface ResponseGetTask {
    'message': string;
    'id'?: number;
    'username'?: string;
    'createTime'?: number;
    'status'?: ResponseGetTaskStatusEnum;
    'tests'?: Array<string>;
    'nfPrList'?: Array<NfPr>;
}

export const ResponseGetTaskStatusEnum = {
    Pending: 'pending',
    Running: 'running',
    Success: 'success',
    Failed: 'failed',
    Canceled: 'canceled',
} as const;

export type ResponseGetTaskStatusEnum = typeof ResponseGetTaskStatusEnum[keyof typeof ResponseGetTaskStatusEnum];

export interface ResponseGetTasks {
    'message': string;
    'pendingTask'?: Array<TaskSimple>;
    'ongoingTask'?: Array<TaskSimple>;
    'historyTask'?: Array<TaskSimple>;
}
export interface ResponseGetTestLog {
    'message': string;
    'log'?: string;
}
export interface ResponseRegisterRunner {
    'message': string;
    'token'?: string;
}
export interface ResponseRunnerHeartbeat {
    'message': string;
    'id'?: number;
    'tests'?: Array<string>;
    'nfPrList'?: Array<NfPr>;
}
export interface Runner {
    'name': string;
    'ip': string;
    'onGoingTask': number;
    'status': string;
}
export interface TaskSimple {
    'id': number;
    'username': string;
    'createTime': number;
}
export interface Tenant {
    'username': string;
    'role': string;
}
export interface Testcase {
    'name': string;
    'link'?: string;
}

/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add tenants
         * @param {AddTenantsRequest} addTenantsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addTenants: async (addTenantsRequest: AddTenantsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'addTenantsRequest' is not null or undefined
            assertParamExists('addTenants', 'addTenantsRequest', addTenantsRequest)
            const localVarPath = `/api/admin/tenant`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addTenantsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Add testcases
         * @param {AddTestcasesRequest} addTestcasesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addTestcases: async (addTestcasesRequest: AddTestcasesRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'addTestcasesRequest' is not null or undefined
            assertParamExists('addTestcases', 'addTestcasesRequest', addTestcasesRequest)
            const localVarPath = `/api/admin/test/testcase`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addTestcasesRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Cancel task
         * @param {number} id Task ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelTask: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('cancelTask', 'id', id)
            const localVarPath = `/api/test/task`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete runner
         * @param {string} name Runner name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteRunner: async (name: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('deleteRunner', 'name', name)
            const localVarPath = `/api/admin/runner`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete tasks history
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTasksHistory: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/admin/test/history`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete tenants
         * @param {DeleteTenantsRequest} deleteTenantsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTenants: async (deleteTenantsRequest: DeleteTenantsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deleteTenantsRequest' is not null or undefined
            assertParamExists('deleteTenants', 'deleteTenantsRequest', deleteTenantsRequest)
            const localVarPath = `/api/admin/tenant`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deleteTenantsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete testcases
         * @param {DeleteTestcasesRequest} deleteTestcasesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTestcases: async (deleteTestcasesRequest: DeleteTestcasesRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deleteTestcasesRequest' is not null or undefined
            assertParamExists('deleteTestcases', 'deleteTestcasesRequest', deleteTestcasesRequest)
            const localVarPath = `/api/admin/test/testcase`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deleteTestcasesRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Github PRs
         * @param {GetGithubPRsNfEnum} nf Target network function
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGithubPRs: async (nf: GetGithubPRsNfEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'nf' is not null or undefined
            assertParamExists('getGithubPRs', 'nf', nf)
            const localVarPath = `/api/github`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (nf !== undefined) {
                localVarQueryParameter['nf'] = nf;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get runners
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRunners: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/runner`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get task
         * @param {number} id Task ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTask: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getTask', 'id', id)
            const localVarPath = `/api/test/task`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get tasks
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTasks: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/test/tasks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get tenants
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTenants: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/admin/tenant`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get test log
         * @param {number} id Task ID
         * @param {string} testName Test name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTestLog: async (id: number, testName: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getTestLog', 'id', id)
            // verify required parameter 'testName' is not null or undefined
            assertParamExists('getTestLog', 'testName', testName)
            const localVarPath = `/api/test/testlog`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }

            if (testName !== undefined) {
                localVarQueryParameter['testName'] = testName;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get testcases
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTestcases: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/test/testcase`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Login
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login: async (loginRequest: LoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginRequest' is not null or undefined
            assertParamExists('login', 'loginRequest', loginRequest)
            const localVarPath = `/api/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Register runner
         * @param {RegisterRunnerRequest} registerRunnerRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerRunner: async (registerRunnerRequest: RegisterRunnerRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'registerRunnerRequest' is not null or undefined
            assertParamExists('registerRunner', 'registerRunnerRequest', registerRunnerRequest)
            const localVarPath = `/api/admin/runner`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registerRunnerRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Runner heartbeat
         * @param {RequestRunnerHeartbeat} requestRunnerHeartbeat 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runnerHeartbeat: async (requestRunnerHeartbeat: RequestRunnerHeartbeat, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'requestRunnerHeartbeat' is not null or undefined
            assertParamExists('runnerHeartbeat', 'requestRunnerHeartbeat', requestRunnerHeartbeat)
            const localVarPath = `/api/run/runner/heartbeat`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestRunnerHeartbeat, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Submit task
         * @param {RequestSubmitTask} requestSubmitTask 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitTask: async (requestSubmitTask: RequestSubmitTask, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'requestSubmitTask' is not null or undefined
            assertParamExists('submitTask', 'requestSubmitTask', requestSubmitTask)
            const localVarPath = `/api/test/task`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestSubmitTask, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Test output
         * @param {RequestTestOutput} requestTestOutput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testOutput: async (requestTestOutput: RequestTestOutput, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'requestTestOutput' is not null or undefined
            assertParamExists('testOutput', 'requestTestOutput', requestTestOutput)
            const localVarPath = `/api/run/runner/test-output`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestTestOutput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Add tenants
         * @param {AddTenantsRequest} addTenantsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addTenants(addTenantsRequest: AddTenantsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addTenants(addTenantsRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.addTenants']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Add testcases
         * @param {AddTestcasesRequest} addTestcasesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addTestcases(addTestcasesRequest: AddTestcasesRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addTestcases(addTestcasesRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.addTestcases']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Cancel task
         * @param {number} id Task ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cancelTask(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cancelTask(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.cancelTask']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete runner
         * @param {string} name Runner name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteRunner(name: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteRunner(name, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteRunner']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete tasks history
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteTasksHistory(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteTasksHistory(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteTasksHistory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete tenants
         * @param {DeleteTenantsRequest} deleteTenantsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteTenants(deleteTenantsRequest: DeleteTenantsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteTenants(deleteTenantsRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteTenants']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete testcases
         * @param {DeleteTestcasesRequest} deleteTestcasesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteTestcases(deleteTestcasesRequest: DeleteTestcasesRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteTestcases(deleteTestcasesRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteTestcases']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Github PRs
         * @param {GetGithubPRsNfEnum} nf Target network function
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getGithubPRs(nf: GetGithubPRsNfEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetGithubPRsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getGithubPRs(nf, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getGithubPRs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get runners
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRunners(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetRunnersResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRunners(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getRunners']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get task
         * @param {number} id Task ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTask(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseGetTask>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTask(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getTask']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get tasks
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTasks(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseGetTasks>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTasks(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getTasks']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get tenants
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTenants(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetTenantsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTenants(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getTenants']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get test log
         * @param {number} id Task ID
         * @param {string} testName Test name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTestLog(id: number, testName: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseGetTestLog>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTestLog(id, testName, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getTestLog']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get testcases
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTestcases(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetTestcasesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTestcases(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getTestcases']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Login
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LoginResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.login(loginRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.login']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async logout(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.logout(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.logout']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Register runner
         * @param {RegisterRunnerRequest} registerRunnerRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerRunner(registerRunnerRequest: RegisterRunnerRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseRegisterRunner>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registerRunner(registerRunnerRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.registerRunner']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Runner heartbeat
         * @param {RequestRunnerHeartbeat} requestRunnerHeartbeat 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runnerHeartbeat(requestRunnerHeartbeat: RequestRunnerHeartbeat, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseRunnerHeartbeat>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.runnerHeartbeat(requestRunnerHeartbeat, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.runnerHeartbeat']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Submit task
         * @param {RequestSubmitTask} requestSubmitTask 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async submitTask(requestSubmitTask: RequestSubmitTask, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.submitTask(requestSubmitTask, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.submitTask']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Test output
         * @param {RequestTestOutput} requestTestOutput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testOutput(requestTestOutput: RequestTestOutput, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testOutput(requestTestOutput, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.testOutput']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Add tenants
         * @param {AddTenantsRequest} addTenantsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addTenants(addTenantsRequest: AddTenantsRequest, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponse> {
            return localVarFp.addTenants(addTenantsRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Add testcases
         * @param {AddTestcasesRequest} addTestcasesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addTestcases(addTestcasesRequest: AddTestcasesRequest, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponse> {
            return localVarFp.addTestcases(addTestcasesRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Cancel task
         * @param {number} id Task ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelTask(id: number, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponse> {
            return localVarFp.cancelTask(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete runner
         * @param {string} name Runner name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteRunner(name: string, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponse> {
            return localVarFp.deleteRunner(name, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete tasks history
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTasksHistory(options?: RawAxiosRequestConfig): AxiosPromise<MessageResponse> {
            return localVarFp.deleteTasksHistory(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete tenants
         * @param {DeleteTenantsRequest} deleteTenantsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTenants(deleteTenantsRequest: DeleteTenantsRequest, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponse> {
            return localVarFp.deleteTenants(deleteTenantsRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete testcases
         * @param {DeleteTestcasesRequest} deleteTestcasesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTestcases(deleteTestcasesRequest: DeleteTestcasesRequest, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponse> {
            return localVarFp.deleteTestcases(deleteTestcasesRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Github PRs
         * @param {GetGithubPRsNfEnum} nf Target network function
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGithubPRs(nf: GetGithubPRsNfEnum, options?: RawAxiosRequestConfig): AxiosPromise<GetGithubPRsResponse> {
            return localVarFp.getGithubPRs(nf, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get runners
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRunners(options?: RawAxiosRequestConfig): AxiosPromise<GetRunnersResponse> {
            return localVarFp.getRunners(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get task
         * @param {number} id Task ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTask(id: number, options?: RawAxiosRequestConfig): AxiosPromise<ResponseGetTask> {
            return localVarFp.getTask(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get tasks
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTasks(options?: RawAxiosRequestConfig): AxiosPromise<ResponseGetTasks> {
            return localVarFp.getTasks(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get tenants
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTenants(options?: RawAxiosRequestConfig): AxiosPromise<GetTenantsResponse> {
            return localVarFp.getTenants(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get test log
         * @param {number} id Task ID
         * @param {string} testName Test name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTestLog(id: number, testName: string, options?: RawAxiosRequestConfig): AxiosPromise<ResponseGetTestLog> {
            return localVarFp.getTestLog(id, testName, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get testcases
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTestcases(options?: RawAxiosRequestConfig): AxiosPromise<GetTestcasesResponse> {
            return localVarFp.getTestcases(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Login
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<LoginResponse> {
            return localVarFp.login(loginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.logout(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Register runner
         * @param {RegisterRunnerRequest} registerRunnerRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerRunner(registerRunnerRequest: RegisterRunnerRequest, options?: RawAxiosRequestConfig): AxiosPromise<ResponseRegisterRunner> {
            return localVarFp.registerRunner(registerRunnerRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Runner heartbeat
         * @param {RequestRunnerHeartbeat} requestRunnerHeartbeat 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runnerHeartbeat(requestRunnerHeartbeat: RequestRunnerHeartbeat, options?: RawAxiosRequestConfig): AxiosPromise<ResponseRunnerHeartbeat> {
            return localVarFp.runnerHeartbeat(requestRunnerHeartbeat, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Submit task
         * @param {RequestSubmitTask} requestSubmitTask 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitTask(requestSubmitTask: RequestSubmitTask, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponse> {
            return localVarFp.submitTask(requestSubmitTask, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Test output
         * @param {RequestTestOutput} requestTestOutput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testOutput(requestTestOutput: RequestTestOutput, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.testOutput(requestTestOutput, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Add tenants
     * @param {AddTenantsRequest} addTenantsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addTenants(addTenantsRequest: AddTenantsRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).addTenants(addTenantsRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Add testcases
     * @param {AddTestcasesRequest} addTestcasesRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addTestcases(addTestcasesRequest: AddTestcasesRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).addTestcases(addTestcasesRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Cancel task
     * @param {number} id Task ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public cancelTask(id: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).cancelTask(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete runner
     * @param {string} name Runner name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteRunner(name: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteRunner(name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete tasks history
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteTasksHistory(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteTasksHistory(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete tenants
     * @param {DeleteTenantsRequest} deleteTenantsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteTenants(deleteTenantsRequest: DeleteTenantsRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteTenants(deleteTenantsRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete testcases
     * @param {DeleteTestcasesRequest} deleteTestcasesRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteTestcases(deleteTestcasesRequest: DeleteTestcasesRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteTestcases(deleteTestcasesRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Github PRs
     * @param {GetGithubPRsNfEnum} nf Target network function
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getGithubPRs(nf: GetGithubPRsNfEnum, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getGithubPRs(nf, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get runners
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getRunners(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getRunners(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get task
     * @param {number} id Task ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getTask(id: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getTask(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get tasks
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getTasks(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getTasks(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get tenants
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getTenants(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getTenants(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get test log
     * @param {number} id Task ID
     * @param {string} testName Test name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getTestLog(id: number, testName: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getTestLog(id, testName, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get testcases
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getTestcases(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getTestcases(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Login
     * @param {LoginRequest} loginRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).login(loginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Logout
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public logout(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).logout(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Register runner
     * @param {RegisterRunnerRequest} registerRunnerRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public registerRunner(registerRunnerRequest: RegisterRunnerRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).registerRunner(registerRunnerRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Runner heartbeat
     * @param {RequestRunnerHeartbeat} requestRunnerHeartbeat 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public runnerHeartbeat(requestRunnerHeartbeat: RequestRunnerHeartbeat, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).runnerHeartbeat(requestRunnerHeartbeat, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Submit task
     * @param {RequestSubmitTask} requestSubmitTask 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public submitTask(requestSubmitTask: RequestSubmitTask, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).submitTask(requestSubmitTask, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Test output
     * @param {RequestTestOutput} requestTestOutput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public testOutput(requestTestOutput: RequestTestOutput, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).testOutput(requestTestOutput, options).then((request) => request(this.axios, this.basePath));
    }
}

export const GetGithubPRsNfEnum = {
    Amf: 'amf',
    Ausf: 'ausf',
    Bsf: 'bsf',
    Chf: 'chf',
    N3iwf: 'n3iwf',
    Nef: 'nef',
    Nrf: 'nrf',
    Nssf: 'nssf',
    Pcf: 'pcf',
    Smf: 'smf',
    Tngf: 'tngf',
    Udm: 'udm',
    Udr: 'udr',
    Upf: 'upf',
} as const;
export type GetGithubPRsNfEnum = typeof GetGithubPRsNfEnum[keyof typeof GetGithubPRsNfEnum];


