name: Go

on:
  push:
    branches: [ main ]
  pull_request:

env:
  BACKEND_DIR: controller/backend
  RUNNER_DIR: runner

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.26.2' ]
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - name: Build Backend
        run: cd ${{ env.BACKEND_DIR }} && go build -v ./...

      - name: Test Backend
        run: cd ${{ env.BACKEND_DIR }} && go test -v ./...

      - name: Build Runner
        run: cd ${{ env.RUNNER_DIR }} && go build -v ./...

      - name: Test Runner
        run: cd ${{ env.RUNNER_DIR }} && go test -v ./...

      - name: Make backend
        run: make backend

      - name: Make Runner
        run: make runner
