name: GolangCI-Lint

on:
  push:
    branches: [ main ]
  pull_request:

env:
  BACKEND_DIR: controller/backend
  RUNNER_DIR: runner

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.26.2' ]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/checkout@v4

      - name: Run golangci-lint on Backend
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11.4
          working-directory: ${{ env.BACKEND_DIR }}
          args: ./...

      - name: Run golangci-lint on Runner
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11.4
          working-directory: ${{ env.RUNNER_DIR }}
          args: ./...